export type Product={id:number;name:string;cat:string;price:number;img:string;desc:string;tag:string;ingredients:string};
export const categories=['Все','Бургеры','Комбо','Картофель фри','Курица','Напитки','Десерты'];
export const products:Product[]=[
{id:1,name:'Классический бургер с говядиной',cat:'Бургеры',price:249,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',desc:'Сочная говяжья котлета, расплавленный сыр, хрустящий салат и фирменный соус.',tag:'Популярное',ingredients:'Говяжья котлета, бриошь, сыр, салат, помидор, фирменный соус.'},
{id:2,name:'Двойной чизбургер',cat:'Бургеры',price:329,img:'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=900&q=85',desc:'Две сочные котлеты, двойной сыр и фирменный насыщенный соус.',tag:'Хит',ingredients:'2 говяжьи котлеты, двойной сыр, лук, маринованные огурцы, фирменный соус.'},
{id:3,name:'Хрустящий куриный бургер',cat:'Бургеры',price:279,img:'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=85',desc:'Хрустящая курица, свежий коулслоу и сливочный соус в поджаренной булочке.',tag:'Популярное',ingredients:'Хрустящая курица, коулслоу, салат, майонез, бриошь.'},
{id:4,name:'Острый куриный бургер',cat:'Бургеры',price:289,img:'https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=900&q=85',desc:'Хрустящая курица, острый соус и свежие хрустящие овощи.',tag:'',ingredients:'Острая хрустящая курица, салат, халапеньо, острый соус.'},
{id:5,name:'Бургер BBQ с говядиной',cat:'Бургеры',price:299,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85',desc:'Поджаренная говядина, копчёный BBQ-соус, лук и расплавленный сыр.',tag:'',ingredients:'Говяжья котлета, сыр, BBQ-соус, жареный лук.'},
{id:6,name:'Мега бургер',cat:'Бургеры',price:399,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85',desc:'Большой бургер для настоящего голода: двойная говядина, сыр и много начинки.',tag:'Хит',ingredients:'2 говяжьи котлеты, сыр, салат, помидор, лук, маринованные огурцы, соус.'},
{id:7,name:'Комбо «Классический бургер»',cat:'Комбо',price:379,img:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=85',desc:'Классический бургер, картофель фри и прохладительный напиток.',tag:'',ingredients:'Классический бургер, картофель фри, прохладительный напиток.'},
{id:8,name:'Комбо «Двойной бургер»',cat:'Комбо',price:449,img:'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=900&q=85',desc:'Двойной чизбургер, картофель фри и прохладительный напиток.',tag:'Популярное',ingredients:'Двойной чизбургер, картофель фри, прохладительный напиток.'},
{id:9,name:'Куриное комбо',cat:'Комбо',price:419,img:'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=85',desc:'Хрустящий куриный бургер, картофель фри и прохладительный напиток.',tag:'',ingredients:'Куриный бургер, картофель фри, прохладительный напиток.'},
{id:10,name:'Семейное комбо',cat:'Комбо',price:899,img:'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=85',desc:'Большой набор для всей компании: бургеры, закуски и напитки.',tag:'',ingredients:'2 бургера, куриные кусочки, картофель фри, 2 напитка.'},
{id:11,name:'Картофель фри',cat:'Картофель фри',price:129,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',desc:'Золотистый хрустящий картофель с лёгкой приправой.',tag:'',ingredients:'Картофель, масло, приправа.'},
{id:12,name:'Картофель фри с начинкой',cat:'Картофель фри',price:199,img:'https://images.unsplash.com/photo-1576107232684-1279f390859f?auto=format&fit=crop&w=900&q=85',desc:'Хрустящий картофель фри с сыром и фирменным соусом.',tag:'Популярное',ingredients:'Картофель фри, сырный соус, фирменный соус, приправа.'},
{id:13,name:'Куриные наггетсы',cat:'Курица',price:179,img:'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=85',desc:'Хрустящие кусочки курицы с соусом для макания.',tag:'',ingredients:'Курица, панировка, приправа, соус.'},
{id:14,name:'Луковые кольца',cat:'Курица',price:149,img:'https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=900&q=85',desc:'Хрустящие золотистые луковые кольца со сливочным соусом.',tag:'',ingredients:'Лук, кляр, приправа, соус.'},
{id:15,name:'Coca-Cola',cat:'Напитки',price:79,img:'https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=900&q=85',desc:'Охлаждённый прохладительный напиток.',tag:'',ingredients:'Coca-Cola.'},
{id:16,name:'Свежий лимонад',cat:'Напитки',price:99,img:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85',desc:'Яркий освежающий лимонад.',tag:'',ingredients:'Лимон, вода, сахар, лёд.'},
{id:17,name:'Шоколадный торт',cat:'Десерты',price:159,img:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85',desc:'Насыщенный шоколадный десерт для сладкого завершения.',tag:'',ingredients:'Шоколадный торт, какао, сливки.'},
{id:18,name:'Брауни с мороженым',cat:'Десерты',price:189,img:'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=85',desc:'Тёплый брауни с шариком мороженого.',tag:'Популярное',ingredients:'Шоколадный брауни, ванильное мороженое.'}
];
